<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>DbRouter.Benchmarks</AssemblyName>
    <RootNamespace>DbRouter.Benchmarks</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DbRouter.Core\DbRouter.Core.csproj" />
    <ProjectReference Include="..\..\src\DbRouter.DependencyInjection\DbRouter.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\DbRouter.SqlServer\DbRouter.SqlServer.csproj" />
  </ItemGroup>
</Project>
